Objetivo:

Aplicar técnicas de limpieza, transformación y análisis de datos utilizando las
librerías Pandas y NumPy a partir de una base de datos con inconsistencias similares
a escenarios reales.

Instrucciones generales

• Trabajar en un notebook de Jupyter (.ipynb) o script .py

• El código debe estar comentado y organizado

• Cada respuesta debe incluir:

• Código

• Explicación breve del resultado obtenido

• Justificar decisiones de limpieza cuando sea necesario

In [91]:
# Importe de librerias y tabla de datos:

import pandas as pd
import numpy as np

# Cargar el dataset
data = pd.read_csv('ventas_sucias_5000.csv')
# Mostrar las primeras filas del dataset
display(data)

,cliente,producto,precio,cantidad,pais,metodo_pago,fecha
0,Maria,Monitor,1326.0,NaN,peru,Efectivo,2024-01-01 00:00:00
1,Luisa,Laptop,55.0,2,chile,Tarjeta,2024-01-01 01:00:00
2,Carlos,Monitor,1203.0,9,Colombia,Efectivo,2024-01-01 02:00:00
3,Luisa,Monitor,1304.0,3,Perú,TRANSFERENCIA,2024-01-01 03:00:00
4,Luisa,Monitor,426.0,6,chile,Tarjeta,2024-01-01 04:00:00
...,...,...,...,...,...,...,...
4995,Juan,Laptop,1582.0,8,chile,transferencia,2024-07-27 03:00:00
4996,Carlos,Mouse,1553.0,2,Perú,Tarjeta,2024-07-27 04:00:00
4997,Juan,Monitor,1776.0,2,chile,Efectivo,2024-07-27 05:00:00
4998,Pedro,Laptop,1366.0,8,Chile,TRANSFERENCIA,2024-07-27 06:00:00
4999,Pedro,Mouse,406.0,1,chile,TRANSFERENCIA,2024-07-27 00:00:00

Parte 1 — Exploración de datos (Pandas)
=======================================
Actividades

Cargar la base de datos

Mostrar:

• Primeras filas

• Información general del dataset

• Resumen estadístico

In [92]:
## Obtener información general del dataset
print('#'*100)
print(data.head())

####################################################################################################
  cliente producto  precio cantidad      pais    metodo_pago  \
0   Maria  Monitor  1326.0      NaN      peru       Efectivo
1   Luisa   Laptop    55.0        2     chile        Tarjeta
2  Carlos  Monitor  1203.0        9  Colombia       Efectivo
3   Luisa  Monitor  1304.0        3      Perú  TRANSFERENCIA
4   Luisa  Monitor   426.0        6     chile        Tarjeta

                 fecha
0  2024-01-01 00:00:00
1  2024-01-01 01:00:00
2  2024-01-01 02:00:00
3  2024-01-01 03:00:00
4  2024-01-01 04:00:00

In [93]:
print('#'*100)
print(data.info())

####################################################################################################
<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   cliente      5000 non-null   str
 1   producto     5000 non-null   str
 2   precio       4950 non-null   float64
 3   cantidad     4950 non-null   str
 4   pais         5000 non-null   str
 5   metodo_pago  5000 non-null   str
 6   fecha        5000 non-null   str
dtypes: float64(1), str(6)
memory usage: 273.6 KB
None

In [94]:
print('#'*100)
print(data.describe())
data.isnull().sum()

print('#'*100)

data = data.filter(items=['cliente', 'producto', 'precio', 'cantidad', 'pais', 'metodo_pago', 'fecha'])

####################################################################################################
              precio
count    4950.000000
mean     5053.823434
std     63379.982009
min        10.000000
25%       531.000000
50%      1027.000000
75%      1519.000000
max    999999.000000
####################################################################################################

Respuestas:
----------

¿Cuántas filas y columnas tiene la base de datos?

R: 5000 filas y 7 columnas

¿Qué tipos de datos identificas?

R: Inicialmente solo se identifican solamente str y float

¿Encuentras columnas con problemas o inconsistencias?

R; Cantidad y precio tiene nulos, pais y metodo_pago tienen valores errados o acortados

Parte 2 — Limpieza de datos (Pandas)
====================================
Realiza las siguientes tareas:

• Corregir tipos de datos incorrectos

• Identificar y manejar valores nulos

• Estandarizar columnas de texto:

• País

• Método de pago

• Revisar posibles valores atípicos (outliers)

• Corregir formatos de fecha si es necesario

In [95]:
#Estandarizar tipos de datos
data['fecha'] = pd.to_datetime(data['fecha'], errors='coerce') 
data['cantidad'] = pd.to_numeric(data['cantidad'], errors='coerce')

# Verificar los tipos de datos después de la conversión
print(data.dtypes)

cliente                   str
producto                  str
precio                float64
cantidad              float64
pais                      str
metodo_pago               str
fecha          datetime64[us]
dtype: object

In [96]:
# Manejo de nulos
data['cantidad'] = data['cantidad'].fillna(0)
data['precio'] = data['precio'].fillna(0)

print(data.isnull().sum())

display(data)

cliente        0
producto       0
precio         0
cantidad       0
pais           0
metodo_pago    0
fecha          0
dtype: int64

,cliente,producto,precio,cantidad,pais,metodo_pago,fecha
0,Maria,Monitor,1326.0,0.0,peru,Efectivo,2024-01-01 00:00:00
1,Luisa,Laptop,55.0,2.0,chile,Tarjeta,2024-01-01 01:00:00
2,Carlos,Monitor,1203.0,9.0,Colombia,Efectivo,2024-01-01 02:00:00
3,Luisa,Monitor,1304.0,3.0,Perú,TRANSFERENCIA,2024-01-01 03:00:00
4,Luisa,Monitor,426.0,6.0,chile,Tarjeta,2024-01-01 04:00:00
...,...,...,...,...,...,...,...
4995,Juan,Laptop,1582.0,8.0,chile,transferencia,2024-07-27 03:00:00
4996,Carlos,Mouse,1553.0,2.0,Perú,Tarjeta,2024-07-27 04:00:00
4997,Juan,Monitor,1776.0,2.0,chile,Efectivo,2024-07-27 05:00:00
4998,Pedro,Laptop,1366.0,8.0,Chile,TRANSFERENCIA,2024-07-27 06:00:00
4999,Pedro,Mouse,406.0,1.0,chile,TRANSFERENCIA,2024-07-27 00:00:00

In [97]:
#Estandarizar de columnas de texto
print("#"*100)
print(data['cliente'].unique())
print(data['producto'].unique())
print(data['pais'].unique())
print(data['metodo_pago'].unique())

print("#"*100)

data['metodo_pago'] = data['metodo_pago'].str.lower().str.strip()
print(data['metodo_pago'].unique())

data['pais'] = data['pais'].str.lower().str.strip()
print(data['pais'].unique())

#ajustar Col y perú
data['pais'] = data['pais'].replace({'col': 'colombia', 'perú': 'peru'})
print(data['pais'].unique())

####################################################################################################
<StringArray>
['Maria', 'Luisa', 'Carlos', 'Juan', 'Pedro', 'Ana']
Length: 6, dtype: str
<StringArray>
['Monitor', 'Laptop', 'Celular', 'Mouse', 'Teclado']
Length: 5, dtype: str
<StringArray>
['peru', 'chile', 'Colombia', 'Perú', 'COL', 'Chile', 'col']
Length: 7, dtype: str
<StringArray>
['Efectivo', 'Tarjeta', 'TRANSFERENCIA', 'transferencia']
Length: 4, dtype: str
####################################################################################################
<StringArray>
['efectivo', 'tarjeta', 'transferencia']
Length: 3, dtype: str
<StringArray>
['peru', 'chile', 'colombia', 'perú', 'col']
Length: 5, dtype: str
<StringArray>
['peru', 'chile', 'colombia']
Length: 3, dtype: str

In [98]:
#normalizar precios = a 9999 con la media de precios
data['precio'] = data['precio'].replace(999999, data['precio'].mean())   
data['precio'] = data['precio'].round(2)
data.describe()

            precio     cantidad                       fecha
count  5000.000000  5000.000000                        5000
mean   1023.302360     4.854800  2024-04-14 18:44:59.280000
min       0.000000     0.000000         2024-01-01 00:00:00
25%     514.000000     3.000000         2024-02-22 06:45:00
50%    1012.500000     5.000000         2024-04-14 14:30:00
75%    1514.000000     7.000000         2024-06-05 14:15:00
max    5003.290000     9.000000         2024-12-04 00:00:00
std     628.710477     2.646945                         NaN

In [99]:
print(data['fecha'].unique())

<DatetimeArray>
['2024-01-01 00:00:00', '2024-01-01 01:00:00', '2024-01-01 02:00:00',
 '2024-01-01 03:00:00', '2024-01-01 04:00:00', '2024-01-01 05:00:00',
 '2024-01-01 06:00:00', '2024-01-01 07:00:00', '2024-01-01 08:00:00',
 '2024-01-01 09:00:00',
 ...
 '2024-07-26 21:00:00', '2024-07-26 22:00:00', '2024-07-26 23:00:00',
 '2024-07-27 00:00:00', '2024-07-27 01:00:00', '2024-07-27 02:00:00',
 '2024-07-27 03:00:00', '2024-07-27 04:00:00', '2024-07-27 05:00:00',
 '2024-07-27 06:00:00']
Length: 4825, dtype: datetime64[us]

Respuestas:
-----------

¿Qué problemas encontraste?

R: Precio tenia valores incongruentes, pais tenia ortagrafía diferente para Perú y Colombia, los decimales del precio de Venta muy extensos

¿Cómo los solucionaste?

R: para el precio se reemplasa los valores de 99999 con la media de las ventas, en pais se cambia primero el campo todo a minúsculas y se reemplazan los valores errados, se redondean los decimales a máximo 2

¿Eliminaste registros? ¿Por qué?

R: los nulos, para poder dejar una base limpia y congruente.

Parte 3 — Análisis con Pandas
=============================
Actividades

• Crear una nueva columna llamada total: df['total'] = df['precio'] * df['cantidad']

Obtener:

• Total vendido

• Promedio de ventas

• Venta máxima

• Venta mínima

Identificar:

Los 5 productos con mayor valor vendido

El país con más ventas

In [100]:
#nueva columna total
data['total'] = data['precio'] * data['cantidad']
data['total'] = data['total'].round(2)
display(data)

,cliente,producto,precio,cantidad,pais,metodo_pago,fecha,total
0,Maria,Monitor,1326.0,0.0,peru,efectivo,2024-01-01 00:00:00,0.0
1,Luisa,Laptop,55.0,2.0,chile,tarjeta,2024-01-01 01:00:00,110.0
2,Carlos,Monitor,1203.0,9.0,colombia,efectivo,2024-01-01 02:00:00,10827.0
3,Luisa,Monitor,1304.0,3.0,peru,transferencia,2024-01-01 03:00:00,3912.0
4,Luisa,Monitor,426.0,6.0,chile,tarjeta,2024-01-01 04:00:00,2556.0
...,...,...,...,...,...,...,...,...
4995,Juan,Laptop,1582.0,8.0,chile,transferencia,2024-07-27 03:00:00,12656.0
4996,Carlos,Mouse,1553.0,2.0,peru,tarjeta,2024-07-27 04:00:00,3106.0
4997,Juan,Monitor,1776.0,2.0,chile,efectivo,2024-07-27 05:00:00,3552.0
4998,Pedro,Laptop,1366.0,8.0,chile,transferencia,2024-07-27 06:00:00,10928.0
4999,Pedro,Mouse,406.0,1.0,chile,transferencia,2024-07-27 00:00:00,406.0

In [101]:

# valores de resumen después de la limpieza

total_vendido = data['total'].sum().round(2)
promedio_ventas = data['total'].mean().round(2)
venta_mas_alta = data['total'].max().round(2)
venta_mas_baja = data['total'].min().round(2)


print(f'Total vendido: {total_vendido}')
print(f'Promedio de ventas: {promedio_ventas}')
print(f'Venta más alta: {venta_mas_alta}')
print(f'Venta más baja: {venta_mas_baja}')

productos_mas_vendidos = data.groupby('producto')['cantidad'].sum().sort_values(ascending=False).head(5)
print(f'Productos más vendidos:')
display(productos_mas_vendidos)

paises_mas_vendedores = data.groupby('pais')['total'].sum().sort_values(ascending=False).head(5)
print(f'Países con más ventas:')
display(paises_mas_vendedores)

Total vendido: 24713276.33
Promedio de ventas: 4942.66
Venta más alta: 45029.61
Venta más baja: 0.0
Productos más vendidos:

producto
Mouse      5237.0
Laptop     4842.0
Monitor    4829.0
Celular    4733.0
Teclado    4633.0
Name: cantidad, dtype: float64

Países con más ventas:

pais
colombia    10711024.02
chile        7099717.09
peru         6902535.22
Name: total, dtype: float64

Parte 4 — Introducción a NumPy
==============================
Actividades

• Convertir columnas numéricas a un array de NumPy: data = df[['precio',
'cantidad']].to_numpy()

• Separar columnas utilizando indexación: precios = data[:, 0]
cantidades = data[:, 1]

• Aplicar vectorización para calcular ventas totales: totales = precios *
cantidades

In [ ]:
# manejo de los datos con Numpy
data_np = data[['precio', 'cantidad']].to_numpy()

precios = data_np[:, 0]
cantidades = data_np[:, 1]

totales = precios * cantidades

print(totales[:5])

[    0.   110. 10827.  3912.  2556.]

Parte 5 — Análisis con NumPy
============================
Utilizando funciones de NumPy, calcular:

• Suma total de ventas

• Promedio de ventas

• Venta máxima

• Cantidad de ventas superiores a 1000

In [103]:
suma_totales = np.sum(totales)
print(f'Suma de totales: {suma_totales:.2f}')

promedio_ventas = np.mean(totales)
print(f'Promedio de ventas: {promedio_ventas:.2f}')

max_venta = np.max(totales)
print(f'Venta más alta: {max_venta:.2f}')

cantidad_mayor = np.sum(cantidades > 1000)
print(f'Cantidad de ventas con más de 1000 unidades: {cantidad_mayor}')

Suma de totales: 24713276.33
Promedio de ventas: 4942.66
Venta más alta: 45029.61
Cantidad de ventas con más de 1000 unidades: 0

Respuestas:
-----------

¿Qué ventajas observas al usar NumPy?

R: aunque en las operaciones basicas no hay mucha diferencia con pandas, numpy tiene ventaja sobre el calculo de arreglos como se ve la vectorización

¿Qué significa “vectorización”?

R: permite trabajar sobre muchos datos sin necesidad de bucles

¿Qué hace la expresión data[:, 0]?

R: selecciona todas las filas de la columna 0 que este ejercicio es precio